export const QUESTION_BANK: string[] = [
  "What is my favorite comfort food?",
  "Which city would I love to live in for a year?",
  "Beach, mountains, or a bustling city?",
  "What time of day am I most productive?",
  "What’s my go-to drink order?",
  "Which app do I open the most on my phone?",
  "What’s a movie I can watch on repeat?",
  "Am I a night owl or an early bird?",
  "What’s one thing I can’t live without (besides phone)?",
  "What’s my hidden talent?",
  "What was my favorite subject in school?",
  "If I won a free trip, where would I go?",
  "What’s my dream job?",
  "What’s my biggest pet peeve?",
  "What’s a song I never skip?",
  "Which superhero do I relate to most?",
  "What’s my favorite ice cream flavor?",
  "What’s my most used emoji?",
  "Cats, dogs, or neither?",
  "What’s my ideal weekend plan?",
  "What’s my worst habit?",
  "If I could change one thing in the world, what would it be?",
  "Have I ever seen a UFO?",
  "What’s my favorite movie genre?",
  "Do I believe in ghosts?",
  "Do I like public displays of affection?",
  "What’s my favorite ice cream flavor?",
  "Do I like breakfast for dinner?",
  "If I could eat one food forever, what would it be?",
  "What’s my go-to order at Starbucks?",
  "Do I like camping?",
  "Have I ever been out of the country?",
  "What’s my favorite song?",
  "What’s my dream career?",
  "What’s my biggest insecurity?",
  "Do I pack light or heavy?",
  "What’s my favorite candy?",
  "What was my first job?",
  "What’s the weirdest dream I’ve had?",
  "Did I have a childhood nickname?",
  "Do I shower in the morning or at night?",
  "Comedy or horror?",
  "If I could change one thing about myself, what would it be?",
  "What’s the strangest thing I collect?",
  "What’s my favorite emoji?",
  "What was my favorite subject in school?",
  "Do I believe in fate?",
  "Action or romance?",
  "What was my first car?",
  "Do I prefer adventure or relaxation vacations?",
  "Coke or Pepsi?",
  "If I could live anywhere, where would it be?",
  "What’s my go-to order at a bar?",
  "What’s my dream vacation destination?",
  "Early bird or night owl?",
  "How many alarms do I set in the morning?",
  "What’s my weirdest habit?",
  "What’s my favorite dessert?",
  "What’s the most ridiculous thing I’ve ever bought?",
  "What’s my go-to excuse when I’m late?",
  "Do I believe in luck?",
  "What’s my comfort food?",
  "What’s my favorite sport?",
  "What’s my favorite video game?",
  "What’s my food I absolutely hate?",
  "Do I believe in aliens?",
  "What’s my favorite vegetable?",
  "If I could have one superpower, what would it be?",
  "What’s the funniest thing I’ve ever said?",
  "What’s the most embarrassing thing I’ve ever done?",
  "Chocolate or vanilla?",
  "Cats or dogs?",
  "What’s my biggest weakness?",
  "What’s my favorite type of weather?",
  "Do I prefer baths or showers?",
  "Who do I call when I need advice?",
  "Do I believe in conspiracy theories?",
  "Do I like sushi?",
  "Who do I trust the most?",
  "Did I ever get in trouble at school?",
  "What’s my favorite fruit?",
  "Who do I argue with the most?",
  "Who knows me best already?",
  "Who’s my favorite actress?",
  "Coffee or tea?",
  "What’s my biggest fear?",
  "Hot weather or cold weather?",
  "Do I like giving gifts or receiving them more?",
  "If I could meet anyone (dead or alive), who would it be?",
  "What’s my love language?",
  "Do I prefer road trips or flights?",
  "What’s my favorite place I’ve traveled to?",
  "Have I ever ghosted someone?",
  "iPhone or Android?",
  "If I could instantly learn a skill, what would it be?",
  "What was my favorite childhood toy?",
  "What’s my favorite outdoor activity?",
  "What was my first pet’s name?",
  "Who’s my favorite author?",
  "Did I ever break a bone?",
  "Do I prefer cats or dogs?",
  "Do I hold grudges?",
  "Am I organized at work/school?",
  "Have I ever been in love?",
  "What’s my most-used phrase?",
  "City or countryside?",
  "What was my major in school?",
  "What’s my funniest childhood memory?",
  "What’s my favorite color?",
  "Do I remember birthdays?",
  "What’s my favorite music genre?",
  "Do I prefer phone calls or texts?",
  "Sweet or salty?",
  "Do I prefer small groups or big parties?",
  "If I could time travel, would I go to the past or future?",
  "Do I prefer hugs or handshakes?",
  "What’s my favorite animal?",
  "Gold or silver?",
  "Do I make my bed every day?",
  "Who was my childhood best friend?",
  "What’s the one thing I can’t live without?",
  "What’s one place I want to visit before I die?",
  "Do I prefer going out or staying in?",
  "Do I like theme parks?",
  "Do I believe in horoscopes?",
  "Have I ever sent a text to the wrong person?",
  "What’s the worst haircut I’ve ever had?",
  "Beach or mountains?",
  "Did I have braces as a kid?",
  "What’s my favorite social media platform?",
  "What’s my most embarrassing childhood memory?",
  "Do I like pineapple on pizza?",
  "What’s my favorite TV show?",
  "What’s my proudest achievement?",
  "Do I prefer coffee or tea?",
  "Do I like spicy food?",
  "Am I an introvert or extrovert?",
  "What’s my favorite board game?",
  "What’s my favorite musician/band?",
  "What’s the weirdest thing I’ve ever eaten?",
  "Pizza or burgers?",
  "Book or movie?",
  "What’s my favorite fast-food chain?",
  "What’s the worst fashion trend I’ve followed?",
  "Do I like my current job?",
  "Do I sing in the shower?",
  "If I won the lottery, what’s the first thing I’d buy?",
  "Have I ever been ghosted?",
  "Am I more creative or analytical?",
  "Who was my childhood celebrity crush?",
  "Pancakes or waffles?",
  "Do I like seafood?",
  "Sneakers or sandals?",
  "What’s my favorite time of day?",
  "What’s my go-to karaoke song?",
  "Windows or Mac?",
  "Who’s my favorite actor?",
  "Instagram or TikTok?",
  "Do I believe in karma?",
  "Who was my first kiss?",
  "Do I prefer summer or winter?",
  "What’s my favorite cake flavor?",
  "What’s my favorite restaurant?",
  "What’s my favorite hobby?",
  "What’s my favorite pizza topping?",
  "Am I messy or neat?",
  "Do I prefer sweet or savory foods?",
  "What’s my biggest strength?",
  "Do I believe in love at first sight?",
  "Do I like chocolate?",
  "What’s the clumsiest thing I’ve ever done?",
  "Did I play sports as a kid?",
  "Do I hit snooze or get up immediately?",
  "What’s my favorite season?",
  "What’s my favorite snack?",
  "What’s the most random fact I know?",
  "What’s my favorite drink?",
  "Do I prefer reading or watching TV?",
  "What’s my favorite app?",
  "What subject did I hate most?",
  "What’s my favorite book?",
  "Do I cook or order takeout more often?",
  "What’s my favorite movie?",
  "Did I move houses often as a kid?",
  "What’s the most awkward date I’ve had?",
  "Have I ever failed a class/test?",
  "Netflix or YouTube?",
  "Do I prefer working alone or in teams?",
  "What’s my spirit animal?",
  "Did I skip classes in school?",
  "What city was I born in?",
  "Am I usually late or early?",
  "Do I talk in my sleep?",
  "Do I like surprises?",
  "What’s my favorite podcast?",
  "What was my favorite childhood movie?",
  "What’s my favorite food?",
  "Am I a morning person or a night owl?",
  "Who’s my best friend right now?",
  "Who makes me laugh the most?",
  "Did I ever go to summer camp?",
  "If I could swap lives with someone for a day, who would it be?",
  "What was my favorite cartoon as a kid?",
  "Do I like cruises?",
  "Do I snore?",
  "What’s my favorite sports team?",
  "If I could be famous, what for?",
  "What’s my favorite indoor activity?",
  "What’s my hidden talent?",
  "Do I believe in soulmates?",
  "Do I forgive easily?",
  "What’s my favorite holiday?",
  "What was my least favorite class?",
  "What’s my dream job?",
  "What’s my favorite alcoholic drink?",
  "Do I get motion sickness?",
  "What’s my guilty pleasure TV show?",
  "Who was my first crush?",
  "Have I ever lied to get out of plans?",
  "What’s my biggest pet peeve?"
  ]
