export const QUESTION_BANK: string[] = [
  "Which ice cream flavour would I prefer? (Chocolate, Vanilla, Butterscotch, Black Currant)",
  "Which dessert would I pick first? (Cake, Brownie, Ice Cream, Gulab Jamun)",
  "Which snack would I grab first? (Chips, Biscuits, Chocolate, Fruit)",
  "Which drink would I usually choose? (Coffee, Tea, Juice, Soft Drink)",
  "Which breakfast would I enjoy most? (Dosa, Sandwich, Idli, Paratha)",
  "Which street food would I choose? (Pani Puri, Pav Bhaji, Samosa, Momos)",
  "Which fast food item would I pick? (Burger, Pizza, Fries, Wrap)",
  "Which fruit would I prefer? (Mango, Apple, Banana, Orange)",
  "Which sweet would I choose? (Rasgulla, Jalebi, Laddu, Kaju Katli)",
  "Which cuisine would I like most? (Indian, Chinese, Italian, Mexican)",
  "Which comfort food would suit me best? (Biryani, Maggi, Pizza, Curd Rice)",
  "Which milkshake would I order? (Chocolate, Strawberry, Mango, Vanilla)",
  "Which hot drink would I choose in winter? (Tea, Coffee, Hot Chocolate, Soup)",
  "Which cold drink would I choose in summer? (Lemon Juice, Soft Drink, Iced Tea, Milkshake)",
  "Which type of chocolate would I prefer? (Dark, Milk, White, Nut-filled)",
  "Which bakery item would I choose? (Croissant, Donut, Muffin, Puff)",
  "Which dinner sounds best to me? (Homemade meal, Takeout, Buffet, Cafe food)",
  "Which topping would I pick on pizza? (Extra cheese, Mushroom, Chicken, Corn)",
  "Which flavour of chips would I choose? (Masala, Cream & Onion, Salted, Cheese)",
  "Which festival food would I wait for? (Payasam, Biryani, Sweets, Snacks)",
  "Which café order sounds like me? (Cappuccino, Cold Coffee, Tea, Hot Chocolate)",
  "Which kind of rice dish would I pick? (Fried Rice, Biryani, Curd Rice, Lemon Rice)",
  "Which kind of noodles would I choose? (Hakka Noodles, Schezwan Noodles, Ramen, Maggi)",
  "Which dip would I prefer with snacks? (Ketchup, Mayonnaise, Mint Chutney, Cheese Dip)",
  "Which food mood matches me best? (Spicy, Sweet, Savory, Anything comforting)",
  "Am I more of a day person or a night owl? (Day Person, Night Owl, Depends on work, Neither)",
  "Am I more introverted or extroverted? (Introvert, Extrovert, Ambivert, Depends on company)",
  "Do I usually think with logic or emotion? (Logic, Emotion, Both, Depends on situation)",
  "Am I more organized or spontaneous? (Organized, Spontaneous, Balanced, Chaotic)",
  "How would I handle stress best? (Sleep, Talk to someone, Stay alone, Listen to music)",
  "Am I more calm or expressive? (Calm, Expressive, Quiet but expressive, Mood-based)",
  "Do I forgive easily? (Yes, No, Only after time, Depends on the mistake)",
  "Do I trust people quickly? (Yes, No, Only a few, Depends on vibes)",
  "Am I more emotional or practical? (Emotional, Practical, Balanced, Depends on the issue)",
  "Do I overthink small things? (Yes, No, Sometimes, More than I admit)",
  "How patient am I usually? (Very patient, Somewhat patient, Impatient, Depends on people)",
  "Am I more optimistic or realistic? (Optimistic, Realistic, Balanced, Changes with mood)",
  "When upset, I usually become: (Silent, Emotional, Angry, Detached)",
  "How do I react to compliments? (Smile and accept, Get shy, Deny it, Joke about it)",
  "Which word describes me best? (Kind, Funny, Focused, Sensitive)",
  "Am I more of a planner or last-minute person? (Planner, Last-minute, A mix, Depends on task)",
  "How competitive am I? (Very competitive, Somewhat competitive, Not competitive, Only in fun things)",
  "What drives me more? (Goals, People, Comfort, Curiosity)",
  "Am I usually stubborn or flexible? (Stubborn, Flexible, Balanced, Depends on topic)",
  "Do I like being the center of attention? (Yes, No, Only sometimes, Only with close people)",
  "How quickly do I open up to people? (Very quickly, Slowly, Only to a few, Depends on comfort)",
  "What matters most to me? (Peace, Success, Relationships, Freedom)",
  "How do I usually respond to problems? (Think deeply, Act quickly, Ask advice, Avoid first)",
  "Am I more serious or playful? (Serious, Playful, Balanced, Depends on who I'm with)",
  "How much alone time do I need? (A lot, Some, Very little, Depends on the week)",
  "What kind of place would I rather visit? (Beach, Mountains, City, Countryside)",
  "What would be my ideal vacation style? (Relaxing, Adventure, Exploring Culture, Food Trip)",
  "How would I rather travel? (Solo, With Friends, With Family, With One Close Person)",
  "Would I prefer a luxury trip or a budget trip? (Luxury, Budget, Balanced, Depends on destination)",
  "Do I enjoy road trips? (Yes, No, Only short ones, Only with the right people)",
  "Which weather would I enjoy most on a trip? (Cold, Sunny, Rainy, Windy)",
  "Do I like planning trips in advance? (Yes, No, Only the important parts, Last-minute style)",
  "Would I rather explore food or sightseeing first? (Food, Sightseeing, Shopping, Rest first)",
  "Do I pack light or heavy? (Light, Heavy, Average, Too much always)",
  "Which seat would I usually want while travelling? (Window, Aisle, Middle is fine, Anything available)",
  "What kind of getaway sounds best? (Hill Station, Beach Resort, City Break, Village Stay)",
  "What would I check first before a trip? (Weather, Food spots, Stay details, Budget)",
  "What travel pace fits me best? (Relaxed, Packed schedule, Spontaneous, Balanced)",
  "What would excite me most on a trip? (Nature, Food, Shopping, Photos)",
  "What kind of stay would I prefer? (Hotel, Resort, Homestay, Airbnb)",
  "Would I rather revisit a favourite place or explore a new one? (Revisit favorite, Explore new, Depends on company, Depends on budget)",
  "How early would I reach for a trip? (Very early, On time, Slightly late, At the last moment)",
  "What travel companion would suit me most? (Best friend, Family, Partner, Solo)",
  "What kind of view would I love most? (Ocean, Mountains, City lights, Green fields)",
  "Would I rather have a planned itinerary or free flow? (Planned itinerary, Free flow, Half and half, Depends on trip length)",
  "What kind of photos would I take most while traveling? (Scenery, Food, Selfies, Candid moments)",
  "Would I rather travel for comfort or adventure? (Comfort, Adventure, Both, Depends on mood)",
  "How many days would my perfect trip be? (Weekend, 4-5 days, A week, Longer than a week)",
  "What kind of transport would I enjoy most? (Flight, Train, Car, Bus)",
  "What would I most likely forget on a trip? (Charger, Toiletries, Water bottle, Medicine)",
  "Which type of movie would I most likely choose? (Action, Comedy, Romance, Thriller)",
  "Would I rather watch movies or series? (Movies, Series, YouTube instead, Depends on mood)",
  "Which genre of music would I likely enjoy most? (Pop, Romantic, Hip-hop, Soft/Melody)",
  "Do I rewatch things I love? (Yes, No, Only favorites, Rarely)",
  "Would I rather spend free time with music or silence? (Music, Silence, Podcasts, Depends on mood)",
  "Which platform would I use most? (YouTube, Netflix, Instagram Reels, Spotify)",
  "Do I enjoy concerts or live events? (Yes, No, Only selected ones, Only with friends)",
  "Would I rather watch alone or with others? (Alone, With others, Depends on the content, Either works)",
  "What content would I watch when bored? (Comedy, Travel, Food videos, Random clips)",
  "Do I prefer loud songs or soft songs? (Loud, Soft, Depends on mood, Only lyrics matter)",
  "Which music time suits me most? (Morning, Afternoon, Night, Anytime)",
  "Would I rather read a book or watch a movie? (Book, Movie, Depends on genre, Neither often)",
  "What kind of shows grab my attention? (Thrillers, Sitcoms, Reality shows, Documentaries)",
  "Would I rather watch something new or replay comfort content? (Something new, Comfort content, Depends on mood, Recommendations only)",
  "What entertainment mood fits me best? (Fun, Emotional, Suspense, Relaxing)",
  "Which app would I open most for entertainment? (YouTube, Instagram, Netflix, Spotify)",
  "Would I rather listen to songs or playlists? (Individual songs, Playlists, Podcasts, Depends on mood)",
  "What kind of hero would I root for? (Smart one, Funny one, Strong one, Underdog)",
  "Would I prefer a theatre watch or home watch? (Theatre, Home, Depends on movie, Depends on company)",
  "What kind of comedy do I enjoy? (Sarcastic, Goofy, Situational, Dry humor)",
  "Would I rather watch short videos or long videos? (Short videos, Long videos, Both, Depends on time)",
  "What soundtrack vibe do I like? (Romantic, Energetic, Sad, Lo-fi)",
  "Would I rather dance to a song or just listen? (Dance, Just listen, Depends on crowd, Depends on song)",
  "What kind of ending do I like? (Happy, Bittersweet, Unexpected twist, Open ending)",
  "Would I rather follow celebrities or creators? (Celebrities, Creators, Both, Neither much)",
  "In a group, what role do I usually take? (Leader, Listener, Entertainer, Observer)",
  "What is my texting style? (Fast replies, Late replies, Seen and forgot, Voice notes)",
  "Do I usually like phone calls? (Yes, No, Only with close people, Only when necessary)",
  "Would I rather have a small circle or a big friend group? (Small circle, Big group, A mix, Depends on life phase)",
  "Do I enjoy meeting new people? (Yes, No, Sometimes, Only if comfortable)",
  "Would I rather talk online or in person? (Online, In person, Voice calls, Depends on topic)",
  "Do I like group outings? (Yes, No, Only if the group is right, Only small groups)",
  "Am I the one who starts conversations? (Yes, No, Sometimes, Only with known people)",
  "Would I rather listen or talk more? (Listen, Talk, Balanced, Depends on company)",
  "Do I remember special dates well? (Yes, No, Only important ones, I remember but forget to mention)",
  "What matters most to me in friendship? (Honesty, Loyalty, Humor, Support)",
  "How quickly do I reply to close friends? (Instantly, Eventually, When free, Depends on mood)",
  "Would I rather hang out one-on-one or in a group? (One-on-one, Group, Both, Depends on plan)",
  "How do I show I care? (Helping, Listening, Checking in, Spending time)",
  "Would I rather receive updates by text or call? (Text, Call, Voice note, Anything)",
  "What kind of friend am I? (Reliable, Funny, Quietly supportive, Protective)",
  "How likely am I to cancel plans? (Rarely, Sometimes, Often if tired, Depends on who)",
  "Do I prefer deep conversations or casual fun? (Deep conversations, Casual fun, Both, Depends on mood)",
  "Would I rather celebrate with friends or family? (Friends, Family, Both, Small circle only)",
  "How do I react if someone is upset? (Comfort them, Give space, Ask directly, Stay nearby silently)",
  "What kind of message would I send most? (Practical update, Meme, Long text, Voice note)",
  "Would I rather be the planner or just go along? (Planner, Go along, Sometimes plan, Depends on group)",
  "How do I feel about surprise visits? (Love them, Hate them, Only from close people, Depends on timing)",
  "Would I rather keep things private or share openly? (Private, Open, Depends on topic, Only with close people)",
  "How often do I check in on people I care about? (Often, Sometimes, Rarely but meaningfully, When something reminds me)",
  "What would I do first on a free day? (Sleep, Go out, Watch something, Do pending work)",
  "Would I rather stay in or step out? (Stay in, Step out, Depends on mood, Only if plans are good)",
  "How do I usually handle stress? (Sleep, Talk to someone, Listen to music, Stay alone)",
  "Do I like routines? (Yes, No, Only basic ones, I try but fail)",
  "What would I spend money on first? (Food, Clothes, Travel, Gadgets)",
  "What kind of morning do I prefer? (Slow and quiet, Productive, Sleepy, Chaotic but fun)",
  "Do I enjoy exercising? (Yes, No, On and off, Only if fun)",
  "What would I rather do after work? (Rest, Go out, Watch something, Talk to someone)",
  "Do I like shopping? (Yes, No, Only when needed, Only online)",
  "Would I rather cook or order food? (Cook, Order food, Depends on mood, Depends on energy)",
  "How do I start my day? (Tea/Coffee, Phone first, Freshen up first, Sleep more)",
  "What kind of workspace suits me? (Very neat, Functional, Messy but manageable, Creative chaos)",
  "How do I tackle deadlines? (Finish early, Last minute, Steady pace, Panic then finish)",
  "Do I prefer working in silence or with background sound? (Silence, Background sound, Music only, Depends on task)",
  "How likely am I to procrastinate? (Very likely, Sometimes, Rarely, Only when not interested)",
  "Would I rather save money or enjoy spending? (Save, Spend, Balanced, Depends on the reason)",
  "How do I usually keep notes? (Phone, Notebook, Mental notes, Sticky notes)",
  "What habit sounds most like me? (Making lists, Forgetting things, Double-checking, Doing things late)",
  "Would I rather multitask or focus on one thing? (Multitask, One thing at a time, Depends on work, Whatever works)",
  "How would I spend a quiet evening? (Watch something, Read/scroll, Talk to someone, Just rest)",
  "What motivates me more? (Goals, Deadlines, People, Mood)",
  "Would I rather wake up early or sleep late? (Wake up early, Sleep late, Depends on schedule, Neither ideally)",
  "What kind of room vibe do I like? (Minimal, Cozy, Bright and colorful, A little messy)",
  "How do I react to sudden plans? (Excited, Annoyed, Depends on who, Depends on my mood)",
  "Would I rather own fewer good things or many average things? (Fewer good things, Many average things, Balanced, Depends on category)",
  "If I were an animal, what would suit me best? (Cat, Dog, Lion, Dolphin)",
  "If I suddenly got a free ticket, where would I use it? (Beach destination, Hill station, Foreign city, Back home)",
  "If I won a big amount of money, what would I do first? (Travel, Save/invest, Buy something big, Help family)",
  "What kind of surprise would I enjoy most? (Gift, Trip, Food treat, Heartfelt message)",
  "Which superpower would I choose? (Flying, Invisibility, Time travel, Mind reading)",
  "What kind of pet would I most likely want? (Dog, Cat, Fish, No pets)",
  "If I could master one hobby instantly, what would I choose? (Singing, Dancing, Cooking, Photography)",
  "What kind of birthday would I prefer? (Big party, Small gathering, Quiet day, Trip)",
  "If I vanish for a day, where am I likely to be? (Sleeping, Traveling, With close people, Offline and chilling)",
  "Which type of person do I usually admire? (Kind people, Smart people, Confident people, Funny people)",
  "If I had to choose one weather forever? (Rainy, Sunny, Cold, Cloudy)",
  "If I were to start a hobby now, what would I pick? (Cooking, Fitness, Photography, Reading)",
  "What kind of gift would make me happiest? (Useful item, Thoughtful handmade, Food treat, Experience)",
  "If I could relive one kind of day, what would it be? (Trip day, Festival day, Lazy day at home, Fun outing)",
  "What kind of home vibe would I love? (Minimal and clean, Warm and cozy, Modern and stylish, Lively and colorful)",
  "If I could swap lives for a day, I'd choose: (Traveler, Artist, Celebrity, No one)",
  "What kind of surprise plan would I enjoy? (Cafe date, Road trip, Gift at home, Simple quality time)",
  "If I had to delete one app type, I'd sacrifice: (Games, Shopping apps, Social media, Music apps)",
  "What kind of compliment would stay with me? (About my looks, About my work, About my heart, About my effort)",
  "If I were in a movie, I'd play: (Main character, Funny side character, Quiet intelligent one, Unexpected twist character)",
  "What kind of home meal would feel special? (Simple comfort food, Big family spread, Restaurant-style meal, Breakfast for dinner)",
  "If I could instantly improve one skill, it would be: (Communication, Confidence, Cooking, Time management)",
  "What random thing would I most likely collect? (Books, Mugs, Photos, Memories)",
  "If I had a free evening in a new city, I'd pick: (Food hunt, Walk around, Cafe sit-down, Shopping)",
  "What kind of festival memory would I treasure most? (Food, Family time, Photos, Dress-up)",
  "Which phone app would I open first in the morning? (WhatsApp, Instagram, Clock, YouTube)",
  "Would I rather spend a rainy evening with chai or coffee? (Chai, Coffee, Hot Chocolate, Soup)",
  "What kind of shoes would I choose most often? (Sneakers, Sandals, Formal shoes, Slippers)",
  "What would I most likely forget before leaving home? (Wallet, Keys, Phone charger, Water bottle)",
  "How do I usually celebrate small wins? (Food treat, Buy something small, Tell someone, Just smile and move on)",
  "Which meal outside would I choose most often? (Cafe brunch, Dinner outing, Street food, Dessert outing)",
  "Would I rather wear a watch or a bracelet? (Watch, Bracelet, Both, Neither)",
  "Which phone setting matters most to me? (Battery, Storage, Camera, Brightness)",
  "What do I notice first in a place? (Cleanliness, Ambience, People, Food options)",
  "Would I rather receive flowers or food? (Flowers, Food, A handwritten note, Anything thoughtful)",
  "Which sound relaxes me most? (Rain, Music, Silence, Fan/white noise)",
  "How do I usually spend waiting time? (Phone scrolling, Observing people, Listening to music, Thinking)",
  "Would I rather work from home or outside? (Home, Office/Cafe, Hybrid, Depends on work)",
  "Which time of day feels most like me? (Morning, Afternoon, Evening, Late night)",
  "What type of joke would make me laugh fastest? (Sarcastic, Unexpected, Relatable, Silly)",
  "Would I rather keep a tidy bag or a chaotic bag? (Tidy, Chaotic, Depends on the day, Organized enough)",
  "Which celebration would I enjoy most? (Birthday, Festival, Achievement party, Quiet dinner)",
  "If I had one extra hour daily, I’d use it for: (Sleep, A hobby, Talking to people, Watching something)",
  "What would I value more in a room/stay? (View, Comfort, Aesthetics, Price)",
  "Which sort of evening outing would I choose? (Cafe, Walk, Shopping, Movie)",
  "Would I rather get ready quickly or take my time? (Quickly, Take my time, Depends on event, Always late)",
  "What kind of planner am I? (Digital planner, Mental planner, Notebook planner, Not really a planner)",
  "Would I rather own more books or more clothes? (Books, Clothes, Equal mix, Neither much)",
  "What inspires me more? (People's stories, Nature, Success stories, Art/music)",
  "Which photo moment would I save first? (Sunset, Food plate, Candid selfie, Group photo)",
  "Which option best describes my ideal breakfast? (South Indian, Bread-based, Healthy bowl, Skip breakfast)",
  "What would I most likely choose for my ideal breakfast? (South Indian, Bread-based, Healthy bowl, Skip breakfast)",
  "Which one would suit me most when it comes to my ideal breakfast? (South Indian, Bread-based, Healthy bowl, Skip breakfast)",
  "If you had to guess my ideal breakfast, what would you pick? (South Indian, Bread-based, Healthy bowl, Skip breakfast)",
  "When it comes to my ideal breakfast, what would I lean toward? (South Indian, Bread-based, Healthy bowl, Skip breakfast)",
  "Which choice fits me best for my ideal breakfast? (South Indian, Bread-based, Healthy bowl, Skip breakfast)",
  "What seems most like me regarding my ideal breakfast? (South Indian, Bread-based, Healthy bowl, Skip breakfast)",
  "If I had to decide on my ideal breakfast, what would I select? (South Indian, Bread-based, Healthy bowl, Skip breakfast)",
  "Which one sounds closest to me for my ideal breakfast? (South Indian, Bread-based, Healthy bowl, Skip breakfast)",
  "What would probably be my answer for my ideal breakfast? (South Indian, Bread-based, Healthy bowl, Skip breakfast)",
  "Which of these feels most like me about my ideal breakfast? (South Indian, Bread-based, Healthy bowl, Skip breakfast)",
  "What is my likely pick for my ideal breakfast? (South Indian, Bread-based, Healthy bowl, Skip breakfast)",
  "Which option best describes my wardrobe style? (Simple, Trendy, Comfortable, Mixed)",
  "What would I most likely choose for my wardrobe style? (Simple, Trendy, Comfortable, Mixed)",
  "Which one would suit me most when it comes to my wardrobe style? (Simple, Trendy, Comfortable, Mixed)",
  "If you had to guess my wardrobe style, what would you pick? (Simple, Trendy, Comfortable, Mixed)",
  "When it comes to my wardrobe style, what would I lean toward? (Simple, Trendy, Comfortable, Mixed)",
  "Which choice fits me best for my wardrobe style? (Simple, Trendy, Comfortable, Mixed)",
  "What seems most like me regarding my wardrobe style? (Simple, Trendy, Comfortable, Mixed)",
  "If I had to decide on my wardrobe style, what would I select? (Simple, Trendy, Comfortable, Mixed)",
  "Which one sounds closest to me for my wardrobe style? (Simple, Trendy, Comfortable, Mixed)",
  "What would probably be my answer for my wardrobe style? (Simple, Trendy, Comfortable, Mixed)",
  "Which of these feels most like me about my wardrobe style? (Simple, Trendy, Comfortable, Mixed)",
  "What is my likely pick for my wardrobe style? (Simple, Trendy, Comfortable, Mixed)",
  "Which option best describes my evening choice? (Cafe, Home, Walk, Movie)",
  "What would I most likely choose for my evening choice? (Cafe, Home, Walk, Movie)",
  "Which one would suit me most when it comes to my evening choice? (Cafe, Home, Walk, Movie)",
  "If you had to guess my evening choice, what would you pick? (Cafe, Home, Walk, Movie)",
  "When it comes to my evening choice, what would I lean toward? (Cafe, Home, Walk, Movie)",
  "Which choice fits me best for my evening choice? (Cafe, Home, Walk, Movie)",
  "What seems most like me regarding my evening choice? (Cafe, Home, Walk, Movie)",
  "If I had to decide on my evening choice, what would I select? (Cafe, Home, Walk, Movie)",
  "Which one sounds closest to me for my evening choice? (Cafe, Home, Walk, Movie)",
  "What would probably be my answer for my evening choice? (Cafe, Home, Walk, Movie)",
  "Which of these feels most like me about my evening choice? (Cafe, Home, Walk, Movie)",
  "What is my likely pick for my evening choice? (Cafe, Home, Walk, Movie)",
  "Which option best describes my reaction to free time? (Sleep, Plan something, Watch content, Do nothing happily)",
  "What would I most likely choose for my reaction to free time? (Sleep, Plan something, Watch content, Do nothing happily)",
  "Which one would suit me most when it comes to my reaction to free time? (Sleep, Plan something, Watch content, Do nothing happily)",
  "If you had to guess my reaction to free time, what would you pick? (Sleep, Plan something, Watch content, Do nothing happily)",
  "When it comes to my reaction to free time, what would I lean toward? (Sleep, Plan something, Watch content, Do nothing happily)",
  "Which choice fits me best for my reaction to free time? (Sleep, Plan something, Watch content, Do nothing happily)",
  "What seems most like me regarding my reaction to free time? (Sleep, Plan something, Watch content, Do nothing happily)",
  "If I had to decide on my reaction to free time, what would I select? (Sleep, Plan something, Watch content, Do nothing happily)",
  "Which one sounds closest to me for my reaction to free time? (Sleep, Plan something, Watch content, Do nothing happily)",
  "What would probably be my answer for my reaction to free time? (Sleep, Plan something, Watch content, Do nothing happily)",
  "Which of these feels most like me about my reaction to free time? (Sleep, Plan something, Watch content, Do nothing happily)",
  "What is my likely pick for my reaction to free time? (Sleep, Plan something, Watch content, Do nothing happily)",
  "Which option best describes my celebration style? (Big party, Small dinner, Trip, Quiet celebration)",
  "What would I most likely choose for my celebration style? (Big party, Small dinner, Trip, Quiet celebration)",
  "Which one would suit me most when it comes to my celebration style? (Big party, Small dinner, Trip, Quiet celebration)",
  "If you had to guess my celebration style, what would you pick? (Big party, Small dinner, Trip, Quiet celebration)",
  "When it comes to my celebration style, what would I lean toward? (Big party, Small dinner, Trip, Quiet celebration)",
  "Which choice fits me best for my celebration style? (Big party, Small dinner, Trip, Quiet celebration)",
  "What seems most like me regarding my celebration style? (Big party, Small dinner, Trip, Quiet celebration)",
  "If I had to decide on my celebration style, what would I select? (Big party, Small dinner, Trip, Quiet celebration)",
  "Which one sounds closest to me for my celebration style? (Big party, Small dinner, Trip, Quiet celebration)",
  "What would probably be my answer for my celebration style? (Big party, Small dinner, Trip, Quiet celebration)",
  "Which of these feels most like me about my celebration style? (Big party, Small dinner, Trip, Quiet celebration)",
  "What is my likely pick for my celebration style? (Big party, Small dinner, Trip, Quiet celebration)",
  "Which option best describes my phone usage? (Calls, Texts, Reels, Music)",
  "What would I most likely choose for my phone usage? (Calls, Texts, Reels, Music)",
  "Which one would suit me most when it comes to my phone usage? (Calls, Texts, Reels, Music)",
  "If you had to guess my phone usage, what would you pick? (Calls, Texts, Reels, Music)",
  "When it comes to my phone usage, what would I lean toward? (Calls, Texts, Reels, Music)",
  "Which choice fits me best for my phone usage? (Calls, Texts, Reels, Music)",
  "What seems most like me regarding my phone usage? (Calls, Texts, Reels, Music)",
  "If I had to decide on my phone usage, what would I select? (Calls, Texts, Reels, Music)",
  "Which one sounds closest to me for my phone usage? (Calls, Texts, Reels, Music)",
  "What would probably be my answer for my phone usage? (Calls, Texts, Reels, Music)",
  "Which of these feels most like me about my phone usage? (Calls, Texts, Reels, Music)",
  "What is my likely pick for my phone usage? (Calls, Texts, Reels, Music)",
  "Which option best describes my book or movie mood? (Romance, Mystery, Comedy, Motivation)",
  "What would I most likely choose for my book or movie mood? (Romance, Mystery, Comedy, Motivation)",
  "Which one would suit me most when it comes to my book or movie mood? (Romance, Mystery, Comedy, Motivation)",
  "If you had to guess my book or movie mood, what would you pick? (Romance, Mystery, Comedy, Motivation)",
  "When it comes to my book or movie mood, what would I lean toward? (Romance, Mystery, Comedy, Motivation)",
  "Which choice fits me best for my book or movie mood? (Romance, Mystery, Comedy, Motivation)",
  "What seems most like me regarding my book or movie mood? (Romance, Mystery, Comedy, Motivation)",
  "If I had to decide on my book or movie mood, what would I select? (Romance, Mystery, Comedy, Motivation)",
  "Which one sounds closest to me for my book or movie mood? (Romance, Mystery, Comedy, Motivation)",
  "What would probably be my answer for my book or movie mood? (Romance, Mystery, Comedy, Motivation)",
  "Which of these feels most like me about my book or movie mood? (Romance, Mystery, Comedy, Motivation)",
  "What is my likely pick for my book or movie mood? (Romance, Mystery, Comedy, Motivation)",
  "Which option best describes my favorite classroom seat? (Front, Middle, Back, Anywhere)",
  "What would I most likely choose for my favorite classroom seat? (Front, Middle, Back, Anywhere)",
  "Which one would suit me most when it comes to my favorite classroom seat? (Front, Middle, Back, Anywhere)",
  "If you had to guess my favorite classroom seat, what would you pick? (Front, Middle, Back, Anywhere)",
  "When it comes to my favorite classroom seat, what would I lean toward? (Front, Middle, Back, Anywhere)",
  "Which choice fits me best for my favorite classroom seat? (Front, Middle, Back, Anywhere)",
  "What seems most like me regarding my favorite classroom seat? (Front, Middle, Back, Anywhere)",
  "If I had to decide on my favorite classroom seat, what would I select? (Front, Middle, Back, Anywhere)",
  "Which one sounds closest to me for my favorite classroom seat? (Front, Middle, Back, Anywhere)",
  "What would probably be my answer for my favorite classroom seat? (Front, Middle, Back, Anywhere)",
  "Which of these feels most like me about my favorite classroom seat? (Front, Middle, Back, Anywhere)",
  "What is my likely pick for my favorite classroom seat? (Front, Middle, Back, Anywhere)",
  "Which option best describes my travel companion? (Best friend, Family, Solo, Partner)",
  "What would I most likely choose for my travel companion? (Best friend, Family, Solo, Partner)",
  "Which one would suit me most when it comes to my travel companion? (Best friend, Family, Solo, Partner)",
  "If you had to guess my travel companion, what would you pick? (Best friend, Family, Solo, Partner)",
  "When it comes to my travel companion, what would I lean toward? (Best friend, Family, Solo, Partner)",
  "Which choice fits me best for my travel companion? (Best friend, Family, Solo, Partner)",
  "What seems most like me regarding my travel companion? (Best friend, Family, Solo, Partner)",
  "If I had to decide on my travel companion, what would I select? (Best friend, Family, Solo, Partner)",
  "Which one sounds closest to me for my travel companion? (Best friend, Family, Solo, Partner)",
  "What would probably be my answer for my travel companion? (Best friend, Family, Solo, Partner)",
  "Which of these feels most like me about my travel companion? (Best friend, Family, Solo, Partner)",
  "What is my likely pick for my travel companion? (Best friend, Family, Solo, Partner)",
  "Which option best describes my rain plan? (Stay in, Go for chai, Take photos, Sleep)",
  "What would I most likely choose for my rain plan? (Stay in, Go for chai, Take photos, Sleep)",
  "Which one would suit me most when it comes to my rain plan? (Stay in, Go for chai, Take photos, Sleep)",
  "If you had to guess my rain plan, what would you pick? (Stay in, Go for chai, Take photos, Sleep)",
  "When it comes to my rain plan, what would I lean toward? (Stay in, Go for chai, Take photos, Sleep)",
  "Which choice fits me best for my rain plan? (Stay in, Go for chai, Take photos, Sleep)",
  "What seems most like me regarding my rain plan? (Stay in, Go for chai, Take photos, Sleep)",
  "If I had to decide on my rain plan, what would I select? (Stay in, Go for chai, Take photos, Sleep)",
  "Which one sounds closest to me for my rain plan? (Stay in, Go for chai, Take photos, Sleep)",
  "What would probably be my answer for my rain plan? (Stay in, Go for chai, Take photos, Sleep)",
  "Which of these feels most like me about my rain plan? (Stay in, Go for chai, Take photos, Sleep)",
  "What is my likely pick for my rain plan? (Stay in, Go for chai, Take photos, Sleep)",
  "Which option best describes my comfort clothing? (Oversized, Stylish, Traditional, Anything comfy)",
  "What would I most likely choose for my comfort clothing? (Oversized, Stylish, Traditional, Anything comfy)",
  "Which one would suit me most when it comes to my comfort clothing? (Oversized, Stylish, Traditional, Anything comfy)",
  "If you had to guess my comfort clothing, what would you pick? (Oversized, Stylish, Traditional, Anything comfy)",
  "When it comes to my comfort clothing, what would I lean toward? (Oversized, Stylish, Traditional, Anything comfy)",
  "Which choice fits me best for my comfort clothing? (Oversized, Stylish, Traditional, Anything comfy)",
  "What seems most like me regarding my comfort clothing? (Oversized, Stylish, Traditional, Anything comfy)",
  "If I had to decide on my comfort clothing, what would I select? (Oversized, Stylish, Traditional, Anything comfy)",
  "Which one sounds closest to me for my comfort clothing? (Oversized, Stylish, Traditional, Anything comfy)",
  "What would probably be my answer for my comfort clothing? (Oversized, Stylish, Traditional, Anything comfy)",
  "Which of these feels most like me about my comfort clothing? (Oversized, Stylish, Traditional, Anything comfy)",
  "What is my likely pick for my comfort clothing? (Oversized, Stylish, Traditional, Anything comfy)",
  "Which option best describes my festival plan? (Dress up, Eat food, Meet people, Rest at home)",
  "What would I most likely choose for my festival plan? (Dress up, Eat food, Meet people, Rest at home)",
  "Which one would suit me most when it comes to my festival plan? (Dress up, Eat food, Meet people, Rest at home)",
  "If you had to guess my festival plan, what would you pick? (Dress up, Eat food, Meet people, Rest at home)",
  "When it comes to my festival plan, what would I lean toward? (Dress up, Eat food, Meet people, Rest at home)",
  "Which choice fits me best for my festival plan? (Dress up, Eat food, Meet people, Rest at home)",
  "What seems most like me regarding my festival plan? (Dress up, Eat food, Meet people, Rest at home)",
  "If I had to decide on my festival plan, what would I select? (Dress up, Eat food, Meet people, Rest at home)",
  "Which one sounds closest to me for my festival plan? (Dress up, Eat food, Meet people, Rest at home)",
  "What would probably be my answer for my festival plan? (Dress up, Eat food, Meet people, Rest at home)",
  "Which of these feels most like me about my festival plan? (Dress up, Eat food, Meet people, Rest at home)",
  "What is my likely pick for my festival plan? (Dress up, Eat food, Meet people, Rest at home)",
  "Which option best describes my first purchase with extra money? (Food, Clothes, Gadget, Trip)",
  "What would I most likely choose for my first purchase with extra money? (Food, Clothes, Gadget, Trip)",
  "Which one would suit me most when it comes to my first purchase with extra money? (Food, Clothes, Gadget, Trip)",
  "If you had to guess my first purchase with extra money, what would you pick? (Food, Clothes, Gadget, Trip)",
  "When it comes to my first purchase with extra money, what would I lean toward? (Food, Clothes, Gadget, Trip)",
  "Which choice fits me best for my first purchase with extra money? (Food, Clothes, Gadget, Trip)",
  "What seems most like me regarding my first purchase with extra money? (Food, Clothes, Gadget, Trip)",
  "If I had to decide on my first purchase with extra money, what would I select? (Food, Clothes, Gadget, Trip)",
  "Which one sounds closest to me for my first purchase with extra money? (Food, Clothes, Gadget, Trip)",
  "What would probably be my answer for my first purchase with extra money? (Food, Clothes, Gadget, Trip)",
  "Which of these feels most like me about my first purchase with extra money? (Food, Clothes, Gadget, Trip)",
  "What is my likely pick for my first purchase with extra money? (Food, Clothes, Gadget, Trip)",
  "Which option best describes the kind of messages I send? (Practical, Funny, Long emotional, Short and quick)",
  "What would I most likely choose for the kind of messages I send? (Practical, Funny, Long emotional, Short and quick)",
  "Which one would suit me most when it comes to the kind of messages I send? (Practical, Funny, Long emotional, Short and quick)",
  "If you had to guess the kind of messages I send, what would you pick? (Practical, Funny, Long emotional, Short and quick)",
  "When it comes to the kind of messages I send, what would I lean toward? (Practical, Funny, Long emotional, Short and quick)",
  "Which choice fits me best for the kind of messages I send? (Practical, Funny, Long emotional, Short and quick)",
  "What seems most like me regarding the kind of messages I send? (Practical, Funny, Long emotional, Short and quick)",
  "If I had to decide on the kind of messages I send, what would I select? (Practical, Funny, Long emotional, Short and quick)",
  "Which one sounds closest to me for the kind of messages I send? (Practical, Funny, Long emotional, Short and quick)",
  "What would probably be my answer for the kind of messages I send? (Practical, Funny, Long emotional, Short and quick)",
  "Which of these feels most like me about the kind of messages I send? (Practical, Funny, Long emotional, Short and quick)",
  "What is my likely pick for the kind of messages I send? (Practical, Funny, Long emotional, Short and quick)",
  "Which option best describes the way I recharge? (Alone time, Music, Friends, Sleep)",
  "What would I most likely choose for the way I recharge? (Alone time, Music, Friends, Sleep)",
  "Which one would suit me most when it comes to the way I recharge? (Alone time, Music, Friends, Sleep)",
  "If you had to guess the way I recharge, what would you pick? (Alone time, Music, Friends, Sleep)",
  "When it comes to the way I recharge, what would I lean toward? (Alone time, Music, Friends, Sleep)",
  "Which choice fits me best for the way I recharge? (Alone time, Music, Friends, Sleep)",
  "What seems most like me regarding the way I recharge? (Alone time, Music, Friends, Sleep)",
  "If I had to decide on the way I recharge, what would I select? (Alone time, Music, Friends, Sleep)",
  "Which one sounds closest to me for the way I recharge? (Alone time, Music, Friends, Sleep)",
  "What would probably be my answer for the way I recharge? (Alone time, Music, Friends, Sleep)",
  "Which of these feels most like me about the way I recharge? (Alone time, Music, Friends, Sleep)",
  "What is my likely pick for the way I recharge? (Alone time, Music, Friends, Sleep)",
  "Which option best describes my small luxury? (Good food, Shopping, Travel, Peace and quiet)",
  "What would I most likely choose for my small luxury? (Good food, Shopping, Travel, Peace and quiet)",
  "Which one would suit me most when it comes to my small luxury? (Good food, Shopping, Travel, Peace and quiet)",
  "If you had to guess my small luxury, what would you pick? (Good food, Shopping, Travel, Peace and quiet)",
  "When it comes to my small luxury, what would I lean toward? (Good food, Shopping, Travel, Peace and quiet)",
  "Which choice fits me best for my small luxury? (Good food, Shopping, Travel, Peace and quiet)",
  "What seems most like me regarding my small luxury? (Good food, Shopping, Travel, Peace and quiet)",
  "If I had to decide on my small luxury, what would I select? (Good food, Shopping, Travel, Peace and quiet)",
  "Which one sounds closest to me for my small luxury? (Good food, Shopping, Travel, Peace and quiet)",
  "What would probably be my answer for my small luxury? (Good food, Shopping, Travel, Peace and quiet)",
  "Which of these feels most like me about my small luxury? (Good food, Shopping, Travel, Peace and quiet)",
  "What is my likely pick for my small luxury? (Good food, Shopping, Travel, Peace and quiet)",
  "Which option best describes my ideal evening vibe? (Walk outside, Cafe time, Movie/show, At home)",
  "What would I most likely choose for my ideal evening vibe? (Walk outside, Cafe time, Movie/show, At home)",
  "Which one would suit me most when it comes to my ideal evening vibe? (Walk outside, Cafe time, Movie/show, At home)",
  "If you had to guess my ideal evening vibe, what would you pick? (Walk outside, Cafe time, Movie/show, At home)",
  "When it comes to my ideal evening vibe, what would I lean toward? (Walk outside, Cafe time, Movie/show, At home)",
  "Which choice fits me best for my ideal evening vibe? (Walk outside, Cafe time, Movie/show, At home)",
  "What seems most like me regarding my ideal evening vibe? (Walk outside, Cafe time, Movie/show, At home)",
  "If I had to decide on my ideal evening vibe, what would I select? (Walk outside, Cafe time, Movie/show, At home)",
  "Which one sounds closest to me for my ideal evening vibe? (Walk outside, Cafe time, Movie/show, At home)",
  "What would probably be my answer for my ideal evening vibe? (Walk outside, Cafe time, Movie/show, At home)",
  "Which of these feels most like me about my ideal evening vibe? (Walk outside, Cafe time, Movie/show, At home)",
  "What is my likely pick for my ideal evening vibe? (Walk outside, Cafe time, Movie/show, At home)",
  "Which option best describes my work desk vibe? (Very neat, Functional, Messy, Aesthetic)",
  "What would I most likely choose for my work desk vibe? (Very neat, Functional, Messy, Aesthetic)",
  "Which one would suit me most when it comes to my work desk vibe? (Very neat, Functional, Messy, Aesthetic)",
  "If you had to guess my work desk vibe, what would you pick? (Very neat, Functional, Messy, Aesthetic)",
  "When it comes to my work desk vibe, what would I lean toward? (Very neat, Functional, Messy, Aesthetic)",
  "Which choice fits me best for my work desk vibe? (Very neat, Functional, Messy, Aesthetic)",
  "What seems most like me regarding my work desk vibe? (Very neat, Functional, Messy, Aesthetic)",
  "If I had to decide on my work desk vibe, what would I select? (Very neat, Functional, Messy, Aesthetic)",
  "Which one sounds closest to me for my work desk vibe? (Very neat, Functional, Messy, Aesthetic)",
  "What would probably be my answer for my work desk vibe? (Very neat, Functional, Messy, Aesthetic)",
  "Which of these feels most like me about my work desk vibe? (Very neat, Functional, Messy, Aesthetic)",
  "What is my likely pick for my work desk vibe? (Very neat, Functional, Messy, Aesthetic)",
  "Which option best describes my response under pressure? (Stay calm, Panic first, Ask for help, Act fast)",
  "What would I most likely choose for my response under pressure? (Stay calm, Panic first, Ask for help, Act fast)",
  "Which one would suit me most when it comes to my response under pressure? (Stay calm, Panic first, Ask for help, Act fast)",
  "If you had to guess my response under pressure, what would you pick? (Stay calm, Panic first, Ask for help, Act fast)",
  "When it comes to my response under pressure, what would I lean toward? (Stay calm, Panic first, Ask for help, Act fast)",
  "Which choice fits me best for my response under pressure? (Stay calm, Panic first, Ask for help, Act fast)",
  "What seems most like me regarding my response under pressure? (Stay calm, Panic first, Ask for help, Act fast)",
  "If I had to decide on my response under pressure, what would I select? (Stay calm, Panic first, Ask for help, Act fast)",
  "Which one sounds closest to me for my response under pressure? (Stay calm, Panic first, Ask for help, Act fast)",
  "What would probably be my answer for my response under pressure? (Stay calm, Panic first, Ask for help, Act fast)",
  "Which of these feels most like me about my response under pressure? (Stay calm, Panic first, Ask for help, Act fast)",
  "What is my likely pick for my response under pressure? (Stay calm, Panic first, Ask for help, Act fast)",
  "Which option best describes my pet choice? (Dog, Cat, Bird, No pets)",
  "What would I most likely choose for my pet choice? (Dog, Cat, Bird, No pets)",
  "Which one would suit me most when it comes to my pet choice? (Dog, Cat, Bird, No pets)",
  "If you had to guess my pet choice, what would you pick? (Dog, Cat, Bird, No pets)",
  "When it comes to my pet choice, what would I lean toward? (Dog, Cat, Bird, No pets)",
  "Which choice fits me best for my pet choice? (Dog, Cat, Bird, No pets)",
  "What seems most like me regarding my pet choice? (Dog, Cat, Bird, No pets)",
  "If I had to decide on my pet choice, what would I select? (Dog, Cat, Bird, No pets)",
  "Which one sounds closest to me for my pet choice? (Dog, Cat, Bird, No pets)",
  "What would probably be my answer for my pet choice? (Dog, Cat, Bird, No pets)",
  "Which of these feels most like me about my pet choice? (Dog, Cat, Bird, No pets)",
  "What is my likely pick for my pet choice? (Dog, Cat, Bird, No pets)",
  "Which option best describes the type of compliments I like? (Looks, Work, Personality, Effort)",
  "What would I most likely choose for the type of compliments I like? (Looks, Work, Personality, Effort)",
  "Which one would suit me most when it comes to the type of compliments I like? (Looks, Work, Personality, Effort)",
  "If you had to guess the type of compliments I like, what would you pick? (Looks, Work, Personality, Effort)",
  "When it comes to the type of compliments I like, what would I lean toward? (Looks, Work, Personality, Effort)",
  "Which choice fits me best for the type of compliments I like? (Looks, Work, Personality, Effort)",
  "What seems most like me regarding the type of compliments I like? (Looks, Work, Personality, Effort)",
  "If I had to decide on the type of compliments I like, what would I select? (Looks, Work, Personality, Effort)",
  "Which one sounds closest to me for the type of compliments I like? (Looks, Work, Personality, Effort)",
  "What would probably be my answer for the type of compliments I like? (Looks, Work, Personality, Effort)",
  "Which of these feels most like me about the type of compliments I like? (Looks, Work, Personality, Effort)",
  "What is my likely pick for the type of compliments I like? (Looks, Work, Personality, Effort)",
  "Which option best describes the gift I would appreciate most? (Handmade, Useful, Expensive, Unexpected)",
  "What would I most likely choose for the gift I would appreciate most? (Handmade, Useful, Expensive, Unexpected)",
  "Which one would suit me most when it comes to the gift I would appreciate most? (Handmade, Useful, Expensive, Unexpected)",
  "If you had to guess the gift I would appreciate most, what would you pick? (Handmade, Useful, Expensive, Unexpected)",
  "When it comes to the gift I would appreciate most, what would I lean toward? (Handmade, Useful, Expensive, Unexpected)",
  "Which choice fits me best for the gift I would appreciate most? (Handmade, Useful, Expensive, Unexpected)",
  "What seems most like me regarding the gift I would appreciate most? (Handmade, Useful, Expensive, Unexpected)",
  "If I had to decide on the gift I would appreciate most, what would I select? (Handmade, Useful, Expensive, Unexpected)",
  "Which one sounds closest to me for the gift I would appreciate most? (Handmade, Useful, Expensive, Unexpected)",
  "What would probably be my answer for the gift I would appreciate most? (Handmade, Useful, Expensive, Unexpected)",
  "Which of these feels most like me about the gift I would appreciate most? (Handmade, Useful, Expensive, Unexpected)",
  "What is my likely pick for the gift I would appreciate most? (Handmade, Useful, Expensive, Unexpected)",
  "Which option best describes my photo caption style? (Funny, Simple, Poetic, No caption)",
  "What would I most likely choose for my photo caption style? (Funny, Simple, Poetic, No caption)",
  "Which one would suit me most when it comes to my photo caption style? (Funny, Simple, Poetic, No caption)",
  "If you had to guess my photo caption style, what would you pick? (Funny, Simple, Poetic, No caption)",
  "When it comes to my photo caption style, what would I lean toward? (Funny, Simple, Poetic, No caption)",
  "Which choice fits me best for my photo caption style? (Funny, Simple, Poetic, No caption)",
  "What seems most like me regarding my photo caption style? (Funny, Simple, Poetic, No caption)",
  "If I had to decide on my photo caption style, what would I select? (Funny, Simple, Poetic, No caption)",
  "Which one sounds closest to me for my photo caption style? (Funny, Simple, Poetic, No caption)",
  "What would probably be my answer for my photo caption style? (Funny, Simple, Poetic, No caption)",
  "Which of these feels most like me about my photo caption style? (Funny, Simple, Poetic, No caption)",
  "What is my likely pick for my photo caption style? (Funny, Simple, Poetic, No caption)",
  "Which option best describes my favored weekend timing? (Morning plans, Afternoon outing, Night hangout, No plans)",
  "What would I most likely choose for my favored weekend timing? (Morning plans, Afternoon outing, Night hangout, No plans)",
  "Which one would suit me most when it comes to my favored weekend timing? (Morning plans, Afternoon outing, Night hangout, No plans)",
  "If you had to guess my favored weekend timing, what would you pick? (Morning plans, Afternoon outing, Night hangout, No plans)",
  "When it comes to my favored weekend timing, what would I lean toward? (Morning plans, Afternoon outing, Night hangout, No plans)",
  "Which choice fits me best for my favored weekend timing? (Morning plans, Afternoon outing, Night hangout, No plans)",
  "What seems most like me regarding my favored weekend timing? (Morning plans, Afternoon outing, Night hangout, No plans)",
  "If I had to decide on my favored weekend timing, what would I select? (Morning plans, Afternoon outing, Night hangout, No plans)",
  "Which one sounds closest to me for my favored weekend timing? (Morning plans, Afternoon outing, Night hangout, No plans)",
  "What would probably be my answer for my favored weekend timing? (Morning plans, Afternoon outing, Night hangout, No plans)",
  "Which of these feels most like me about my favored weekend timing? (Morning plans, Afternoon outing, Night hangout, No plans)",
  "What is my likely pick for my favored weekend timing? (Morning plans, Afternoon outing, Night hangout, No plans)",
  "Which option best describes my favorite outing mood? (Relaxed, Adventurous, Food-focused, Photo-focused)",
  "What would I most likely choose for my favorite outing mood? (Relaxed, Adventurous, Food-focused, Photo-focused)",
  "Which one would suit me most when it comes to my favorite outing mood? (Relaxed, Adventurous, Food-focused, Photo-focused)",
  "If you had to guess my favorite outing mood, what would you pick? (Relaxed, Adventurous, Food-focused, Photo-focused)",
  "When it comes to my favorite outing mood, what would I lean toward? (Relaxed, Adventurous, Food-focused, Photo-focused)",
  "Which choice fits me best for my favorite outing mood? (Relaxed, Adventurous, Food-focused, Photo-focused)",
  "What seems most like me regarding my favorite outing mood? (Relaxed, Adventurous, Food-focused, Photo-focused)",
  "If I had to decide on my favorite outing mood, what would I select? (Relaxed, Adventurous, Food-focused, Photo-focused)",
  "Which one sounds closest to me for my favorite outing mood? (Relaxed, Adventurous, Food-focused, Photo-focused)",
  "What would probably be my answer for my favorite outing mood? (Relaxed, Adventurous, Food-focused, Photo-focused)",
  "Which of these feels most like me about my favorite outing mood? (Relaxed, Adventurous, Food-focused, Photo-focused)",
  "What is my likely pick for my favorite outing mood? (Relaxed, Adventurous, Food-focused, Photo-focused)",
];
